name: CI-GA

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -q pipenv codecov
        pipenv sync --dev

    - name: Lint with flake8
      run: |
        pipenv run flake8

    - name: Test whith pytest
      run: |
        pipenv run pytest libpprotest --cov=libpprotest

    - name: Posting Coverage
      run: |
        pipenv run codecov
